### ISSUE TITLE
desktop tab only available after remote user logs in

### ISSUE THREAD

**Issue by luciandf** [Ylianst/MeshAgent#260]
Hello all,

Not sure if this is the intended usage or not but I can see the desktop tab in the remote client, only after remote user login.
Is it possible to enable the desktop tab before a user logs in so that a remote user can perform the login and work remotely?

**Comment by si458** [comment]
What os/version is the remote device?
What meshcentral are u running?
As the remote tab should always be visible if windows and mac
If its linux it will only display if it detects X11 and u aren't using wayland

**Comment by luciandf** [comment]
the remote client is rocky linux 9.4 and I am running plasma X11 (I have selected that at login screen). Not sure what else to set so that wayland is not involved.

The mesh central server is run under docker from here:

https://github.com/Typhonragewind/meshcentral-docker

**Comment by si458** [comment]
yes changing the selector on the login screen only changes the session when you login not the actually login screen itself

you need to fully disable the wayland
https://github.com/Ylianst/MeshAgent?tab=readme-ov-file#special-note-about-kvm-support-on-linux
or if you dont want to fully disable wayland, you need to change the login screen to use X11 by default

also try the offical docker image `ghcr.io/ylianst/meshcentral:latest`

**Comment by luciandf** [comment]
I will try the official docker image too. At the moment my docker compose file is:

```
version: '3'
services:
    mongodb:
        container_name: meshcentral_db
        restart: always
        image: mongo:latest
        expose:
            - 27017
        volumes:
            - '/home/meshcentral/database:/data/db'
    meshcentral:
        restart: always
        container_name: meshcentral
        depends_on:
            - 'mongodb'
        image: typhonragewind/meshcentral:mongodb-latest
        ports:
            - 8086:443 #MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
        environment:
            - PUID=1007
            - PGID=1007
            - HOSTNAME=https://remote.lucianfilip.com     #your hostname
            - REVERSE_PROXY=192.168.1.252     #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
            - REVERSE_PROXY_TLS_PORT=443
            - IFRAME=false #set to true if you wish to enable iframe support
            - ALLOW_NEW_ACCOUNTS=false    #set to false if you want disable self-service creation of new accounts besides the first (admin)
            - WEBRTC=true  #set to true to enable WebRTC - per documentation it is not officially released with meshcentral, but is solid enough to work with. Use with caution
            - NODE_ENV=production
        volumes:
            - '/home/meshcentral/.meshcentral/data:/opt/meshcentral/meshcentral-data'
            - '/home/meshcentral/.meshcentral/user_files:/opt/meshcentral/meshcentral-files'
            - '/home/meshcentral/.meshcentral/backups:/opt/meshcentral/meshcentral-backups'
```

Will it work if I just change to the official image and redeploy?

I also have another question regarding the WebVNC connection. I have installed tiger vnc server on the client machine and set it up. But I cannot get a connection when I try webvnc. is there a guide on how to setup webvnc with meshcentral?
